### ISSUE TITLE
doesn't compile with 4.06.1

### ISSUE THREAD

**Issue by UnixJunkie** [toolslive/camltc#29]
at least the 0.9.5 in opam:
```
# File "otc.ml", line 27, characters 14-15:
# Error: This expression has type string but an expression was expected of type
#          bytes
# Command exited with code 2.
# Makefile:4: recipe for target 'build' failed
# make: *** [build] Error 10
# make: Leaving directory '/home/berenger/.opam/4.06.1/.opam-switch/build/camltc.0.9.4/src'
```

**Comment by toolslive** [comment]
Getting it to work with 4.06.1 means pretty much means changing the whole API to be `bytes` based iso being `string` based. So any code that uses it will need to be adapted too. I'm not sure that's what you want.

**Comment by UnixJunkie** [comment]
related to https://github.com/toolslive/camltc/pull/32

**Comment by UnixJunkie** [comment]
I want a simple key-value store for ocaml programs, compatible with the latest ocaml release.
Isn't this the right place I should be looking at?

**Comment by toolslive** [comment]
ocaml/ocaml-repository#12186

**Comment by UnixJunkie** [comment]
thanks!
