### ISSUE TITLE
you could depend on batteries (or else)

### ISSUE THREAD

**Issue by UnixJunkie** [toolslive/camltc#31]
and have a lot less code to keep maintaining,
and probably use faster functions ...
For example: prefix_match

**Comment by toolslive** [comment]
`batteries` is yet another kitchen sink. It's better to have a bit of duplication than to depend on libraries like these. Same reasoning goes for `core`.

**Comment by toolslive** [comment]
A kitchen sink library is a library that does almost everything.

**Comment by UnixJunkie** [comment]
I personally hate writing code that I know is already out there and probably written by people more skilled than me. But hey, it's your project, you do as you please.
If you use batteries (I'm one of the maintainers), there is a good documentation and there are unit tests covering a lot of the code base. You don't have those when you hackishly write code to just get a dumb utility function.

**Comment by toolslive** [comment]
Rewriting things that already exist is just one of the forces in play.
Another force is someone considering the use of the library. That person might be using core as his/her preferred eco-system, and then does not want to be forced to add batteries as a dependency (or vice versa). 

Obviously, the ideal situation is to get something like `prefix_match` into the std lib, but that's never going to happen. I guess the policies for the std lib are why core and batteries sprouted into existence in the first place.

**Comment by UnixJunkie** [comment]
the stdlib is also full of non tail rec functions, core and batteries are mostly free from any such function
