### ISSUE TITLE
could we have a packaging or opam branch?

### ISSUE THREAD

**Issue by UnixJunkie** [toolslive/camltc#42]
Hello,

In this branch, the commands:

```
git submodule init
git submodule update
```

would have already been ran, and src/3rd-party
would be put under version control.

This would ease the opam packaging (rm git dep) and make sure the opam package
is working even if some infrastructure is down, because the tarball would then be self-contained.

Thanks a lot,
F.

**Comment by UnixJunkie** [comment]
in this branch and in the future, we would synchronize the src/3rd-party/tokyocabinet once for each camltc tag

**Comment by toolslive** [comment]
> make sure the opam package is working even if some infrastructure is down

This disregards dependencies. 
Anyway, the packaging works fine if you use the commit hash in the package, as seen in the previous package

https://github.com/ocaml/opam-repository/blob/master/packages/camltc/camltc.0.9.6/url

In the end, a commit hash should be preferred over a  tarball, as the latter can be changed after the release, while the former is quite tamper free/proof.

**Comment by UnixJunkie** [comment]
but tarballs are managed by the opam infrastructure: even if github is down, they are mirrored somewhere else

**Comment by toolslive** [comment]
#43
